server:
  port: 8080

litedb:
  node-id: node1
  grpc-port: 9090
  cluster-nodes:
    - id: node1
      host: localhost
      grpc-port: 9090
    - id: node2
      host: localhost
      grpc-port: 9091
    - id: node3
      host: localhost
      grpc-port: 9092