server:
  port: ${SERVER_PORT:8080}

litedb:
  node-id: ${NODE_ID:node1}
  port: ${NODE_PORT:9090}
  nodes:
    - id: node1
      host: node1
      port: 9090
    - id: node2
      host: node2
      port: 9090
    - id: node3
      host: node3
      port: 9090